import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "krello",
  description: "Generated by Grishma",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-[#F5F6F8] `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
